name: Update APT Repo

on:
  push:
    paths:
      - 'pool/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate Packages.gz
      run: |
        sudo apt-get update && sudo apt-get install -y dpkg-dev
        dpkg-scanpackages pool /dev/null | gzip -9c > Packages.gz

    - name: Commit and push updated metadata
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add Packages.gz
        git commit -m "Update APT metadata"
        git push
